name: CI
on: [ push, pull_request ]
jobs:
  build_project:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [ '16.x' ]
        os: [ ubuntu-latest ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Check
        run: yarn run package-check

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true

      - name: BundleMon
        uses: lironer/bundlemon-action@v1

  build_examples:
    name: Build project examples

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [ '16.x' ]
        os: [ ubuntu-latest ]
        example:
          [
            'nodejs',
            'react-craco',
            'react-webpack-5-experiments',
            'webpack-5-experiments',
            'webpack-bundler',
          ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
        with:
          working-directory: examples/${{ matrix.example }}

      - name: Build
        run: CI=false yarn build
        working-directory: examples/${{ matrix.example }}
